AWSTemplateFormatVersion: 2010-09-09
Description: template for S3 

Parameters:
  S3PrefixName:
    Type: String
    Default: raisetech-0713

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${S3PrefixName}-${AWS::StackName}
      AccessControl: Private
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - BucketKeyEnabled: true
            ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256

Outputs:
  S3Bucket:
    Description: S3Bucket
    Value: !Ref S3Bucket
    Export:
      Name: !Sub ${S3PrefixName}-${AWS::StackName}
