AWSTemplateFormatVersion: 2010-09-09
Description: template for EC2 

Parameters:
  VPCStack:
    Type: String
    Default: vpc
  SGStack:
    Type: String
    Default: securitygroup
  EC2AMI:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2

Resources:
  EC2WebServer01:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref EC2AMI
      InstanceType: t2.micro
      KeyName: 'lecture4-key'
      AvailabilityZone: !Select [0, !GetAZs ]
      SubnetId:
        Fn::ImportValue: !Sub ${VPCStack}-PublicSubnet1a
      SecurityGroupIds:
        - Fn::ImportValue: !Sub ${SGStack}-EC2-WebServer
      IamInstanceProfile: !Ref EC2InstanceProfile
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-EC2WebServer01

  EC2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      InstanceProfileName: !Sub ${AWS::StackName}-EC2InstanceProfile
      Path: /
      Roles:
        - Ref: EC2IAMRole

  EC2IAMRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: SSM-role
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore

Outputs:
  EC2WebServer01:
    Description: EC2WebServer01
    Value: !Ref EC2WebServer01
    Export:
      Name: !Sub ${AWS::StackName}-EC2WebServer01
